# This file automates deployment to Firebase Hosting when changes are pushed to my main branch. 
# It ensures that the live site is updated whenever I merge new changes

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test step
        run: echo "This is a test step"
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOP_10_MOVIES_APP }}
          channelId: live
          projectId: top-10-movies-app
